name: baap_trasport_app
description: "This project is build for Maitaing vehicale routes"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  dio: ^5.4.3+1
  mime: ^1.0.5
  image_picker: ^1.1.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3
  go_router: ^14.1.1
  json_annotation: ^4.9.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/env/
    - assets/icons/

  # example:
  fonts:
    - family: GoogoleSans
      fonts:
        - asset: assets/font/GoogleSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
